### ISSUE TITLE
Error when running the prebuilt executable

### ISSUE THREAD

**Issue by ThorvaldAagaard** [dealerv2/DealerV2_4#1]
![image](https://github.com/dealerv2/DealerV2_4/assets/10560652/43ab3b20-fe43-439a-b74a-f93ffe663fac)

Probably some libraries, that is missing

**Comment by dealerv2** [comment]
Those are really standard DLL's; cant think why they are missing except that they might be in a different directory.
In any case I have added the libstdc++.so and libc.so to the stdlib subdirectory.
if you issue the command
ldd dealerv2
it will tell you what libraries it is looking for, in my case
      linux-vdso.so.1 (0x00007ffc42d82000)
      libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1d54ccf000)
      libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1d54be8000)
      libgomp.so.1 => /lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f1d54b9e000)
      libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1d54b7e000)
      libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1d54956000)
      /lib64/ld-linux-x86-64.so.2 (0x00007f1d5515e000

You will notice that the directory for some of these is now:
 /lib/x86_64-linux-gnu/
Does your system have such a directory?
Is there a libstdc++.so file in it?
If there is not, you can try copying the one from the stdlib directory on GitHub and putting it there and seeing if that works.
Greg.

________________________________
From: Thorvald Aagaard ***@***.***>
Sent: 11 November 2023 09:56
To: dealerv2/DealerV2_4 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dealerv2/DealerV2_4] Error when running the prebuilt executable (Issue #1)


[image]<https://user-images.githubusercontent.com/10560652/282258241-43ab3b20-fe43-439a-b74a-f93ffe663fac.png>

Probably some libraries, that is missing

**Comment by ThorvaldAagaard** [comment]
ldd dealerv2 gives this output:
```
(base) thorvald@MMVISION-kontor:/mnt/d/github/dealerv2/Dealer-Version-2-/Prod$ ldd dealerv2
./dealerv2: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./dealerv2)
./dealerv2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./dealerv2)
./dealerv2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./dealerv2)
        linux-vdso.so.1 (0x00007ffd8eb86000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fdd6bd60000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdd6bc11000)
        libgomp.so.1 => /lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fdd6bbcf000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fdd6bbb4000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdd6b9c2000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fdd6c191000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdd6b9bc000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdd6b997000)
```
I have the directory  /lib/x86_64-linux-gnu/ with a bunch of files.
I have only this with the name libstd*.*
![image](https://github.com/dealerv2/DealerV2_4/assets/10560652/3933a3e8-8896-467f-9cbf-755daaaf52fe)

Perhaps I should try to rename it

When compiled with the gcc+++ 10 it works, and the output from ldd is:
```
(base) thorvald@MMVISION-kontor:/mnt/d/github/dealerv2/Dealer-Version-2-/Prod$ ldd dealerv2
        linux-vdso.so.1 (0x00007ffcda3e4000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5423e65000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5423e42000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5423c50000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5423a6e000)
        libgomp.so.1 => /lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f5423a2c000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5423a11000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5424204000)
```

**Comment by dealerv2** [comment]
As of the 2024-06-30 version of the Repo, the binary in Prod will run on the version of WSL that installs Ubuntu 22.04.
